// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin_protocol.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdminMsgTypeId int32

const (
	AdminMsgTypeId_AdminAddConfigReqId AdminMsgTypeId = 21
	AdminMsgTypeId_AdminAddConfigRspId AdminMsgTypeId = 22
	AdminMsgTypeId_AdminDelConfigReqId AdminMsgTypeId = 23
	AdminMsgTypeId_AdminDelConfigRspId AdminMsgTypeId = 24
	AdminMsgTypeId_AdminUpdConfigReqId AdminMsgTypeId = 25
	AdminMsgTypeId_AdminUpdConfigRspId AdminMsgTypeId = 26
	AdminMsgTypeId_AdminGetConfigReqId AdminMsgTypeId = 27
	AdminMsgTypeId_AdminGetConfigRspId AdminMsgTypeId = 28
)

var AdminMsgTypeId_name = map[int32]string{
	21: "AdminAddConfigReqId",
	22: "AdminAddConfigRspId",
	23: "AdminDelConfigReqId",
	24: "AdminDelConfigRspId",
	25: "AdminUpdConfigReqId",
	26: "AdminUpdConfigRspId",
	27: "AdminGetConfigReqId",
	28: "AdminGetConfigRspId",
}
var AdminMsgTypeId_value = map[string]int32{
	"AdminAddConfigReqId": 21,
	"AdminAddConfigRspId": 22,
	"AdminDelConfigReqId": 23,
	"AdminDelConfigRspId": 24,
	"AdminUpdConfigReqId": 25,
	"AdminUpdConfigRspId": 26,
	"AdminGetConfigReqId": 27,
	"AdminGetConfigRspId": 28,
}

func (x AdminMsgTypeId) Enum() *AdminMsgTypeId {
	p := new(AdminMsgTypeId)
	*p = x
	return p
}
func (x AdminMsgTypeId) String() string {
	return proto.EnumName(AdminMsgTypeId_name, int32(x))
}
func (x *AdminMsgTypeId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AdminMsgTypeId_value, data, "AdminMsgTypeId")
	if err != nil {
		return err
	}
	*x = AdminMsgTypeId(value)
	return nil
}
func (AdminMsgTypeId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_96ad09d7473f4a36, []int{0}
}

type AdminAddConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Key                  *string  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	OldValue             *string  `protobuf:"bytes,3,req,name=oldValue" json:"oldValue,omitempty"`
	NewValue             *string  `protobuf:"bytes,4,req,name=newValue" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminAddConfigReq) Reset()         { *m = AdminAddConfigReq{} }
func (m *AdminAddConfigReq) String() string { return proto.CompactTextString(m) }
func (*AdminAddConfigReq) ProtoMessage()    {}
func (*AdminAddConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_96ad09d7473f4a36, []int{0}
}
func (m *AdminAddConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminAddConfigReq.Unmarshal(m, b)
}
func (m *AdminAddConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminAddConfigReq.Marshal(b, m, deterministic)
}
func (dst *AdminAddConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminAddConfigReq.Merge(dst, src)
}
func (m *AdminAddConfigReq) XXX_Size() int {
	return xxx_messageInfo_AdminAddConfigReq.Size(m)
}
func (m *AdminAddConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminAddConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminAddConfigReq proto.InternalMessageInfo

func (m *AdminAddConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *AdminAddConfigReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *AdminAddConfigReq) GetOldValue() string {
	if m != nil && m.OldValue != nil {
		return *m.OldValue
	}
	return ""
}

func (m *AdminAddConfigReq) GetNewValue() string {
	if m != nil && m.NewValue != nil {
		return *m.NewValue
	}
	return ""
}

type AdminAddConfigRsp struct {
	Code                 *int32   `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg               *string  `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminAddConfigRsp) Reset()         { *m = AdminAddConfigRsp{} }
func (m *AdminAddConfigRsp) String() string { return proto.CompactTextString(m) }
func (*AdminAddConfigRsp) ProtoMessage()    {}
func (*AdminAddConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_96ad09d7473f4a36, []int{1}
}
func (m *AdminAddConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminAddConfigRsp.Unmarshal(m, b)
}
func (m *AdminAddConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminAddConfigRsp.Marshal(b, m, deterministic)
}
func (dst *AdminAddConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminAddConfigRsp.Merge(dst, src)
}
func (m *AdminAddConfigRsp) XXX_Size() int {
	return xxx_messageInfo_AdminAddConfigRsp.Size(m)
}
func (m *AdminAddConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminAddConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AdminAddConfigRsp proto.InternalMessageInfo

func (m *AdminAddConfigRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *AdminAddConfigRsp) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

type AdminDelConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Key                  *string  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	OldValue             *string  `protobuf:"bytes,3,req,name=oldValue" json:"oldValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminDelConfigReq) Reset()         { *m = AdminDelConfigReq{} }
func (m *AdminDelConfigReq) String() string { return proto.CompactTextString(m) }
func (*AdminDelConfigReq) ProtoMessage()    {}
func (*AdminDelConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_96ad09d7473f4a36, []int{2}
}
func (m *AdminDelConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminDelConfigReq.Unmarshal(m, b)
}
func (m *AdminDelConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminDelConfigReq.Marshal(b, m, deterministic)
}
func (dst *AdminDelConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminDelConfigReq.Merge(dst, src)
}
func (m *AdminDelConfigReq) XXX_Size() int {
	return xxx_messageInfo_AdminDelConfigReq.Size(m)
}
func (m *AdminDelConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminDelConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminDelConfigReq proto.InternalMessageInfo

func (m *AdminDelConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *AdminDelConfigReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *AdminDelConfigReq) GetOldValue() string {
	if m != nil && m.OldValue != nil {
		return *m.OldValue
	}
	return ""
}

type AdminDelConfigRsp struct {
	Code                 *int32   `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg               *string  `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminDelConfigRsp) Reset()         { *m = AdminDelConfigRsp{} }
func (m *AdminDelConfigRsp) String() string { return proto.CompactTextString(m) }
func (*AdminDelConfigRsp) ProtoMessage()    {}
func (*AdminDelConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_96ad09d7473f4a36, []int{3}
}
func (m *AdminDelConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminDelConfigRsp.Unmarshal(m, b)
}
func (m *AdminDelConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminDelConfigRsp.Marshal(b, m, deterministic)
}
func (dst *AdminDelConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminDelConfigRsp.Merge(dst, src)
}
func (m *AdminDelConfigRsp) XXX_Size() int {
	return xxx_messageInfo_AdminDelConfigRsp.Size(m)
}
func (m *AdminDelConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminDelConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AdminDelConfigRsp proto.InternalMessageInfo

func (m *AdminDelConfigRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *AdminDelConfigRsp) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

type AdminUpdConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Key                  *string  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	OldValue             *string  `protobuf:"bytes,3,req,name=oldValue" json:"oldValue,omitempty"`
	NewValue             *string  `protobuf:"bytes,4,req,name=newValue" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminUpdConfigReq) Reset()         { *m = AdminUpdConfigReq{} }
func (m *AdminUpdConfigReq) String() string { return proto.CompactTextString(m) }
func (*AdminUpdConfigReq) ProtoMessage()    {}
func (*AdminUpdConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_96ad09d7473f4a36, []int{4}
}
func (m *AdminUpdConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUpdConfigReq.Unmarshal(m, b)
}
func (m *AdminUpdConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUpdConfigReq.Marshal(b, m, deterministic)
}
func (dst *AdminUpdConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUpdConfigReq.Merge(dst, src)
}
func (m *AdminUpdConfigReq) XXX_Size() int {
	return xxx_messageInfo_AdminUpdConfigReq.Size(m)
}
func (m *AdminUpdConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUpdConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUpdConfigReq proto.InternalMessageInfo

func (m *AdminUpdConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *AdminUpdConfigReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *AdminUpdConfigReq) GetOldValue() string {
	if m != nil && m.OldValue != nil {
		return *m.OldValue
	}
	return ""
}

func (m *AdminUpdConfigReq) GetNewValue() string {
	if m != nil && m.NewValue != nil {
		return *m.NewValue
	}
	return ""
}

type AdminUpdConfigRsp struct {
	Code                 *int32   `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Errmsg               *string  `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminUpdConfigRsp) Reset()         { *m = AdminUpdConfigRsp{} }
func (m *AdminUpdConfigRsp) String() string { return proto.CompactTextString(m) }
func (*AdminUpdConfigRsp) ProtoMessage()    {}
func (*AdminUpdConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_96ad09d7473f4a36, []int{5}
}
func (m *AdminUpdConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUpdConfigRsp.Unmarshal(m, b)
}
func (m *AdminUpdConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUpdConfigRsp.Marshal(b, m, deterministic)
}
func (dst *AdminUpdConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUpdConfigRsp.Merge(dst, src)
}
func (m *AdminUpdConfigRsp) XXX_Size() int {
	return xxx_messageInfo_AdminUpdConfigRsp.Size(m)
}
func (m *AdminUpdConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUpdConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUpdConfigRsp proto.InternalMessageInfo

func (m *AdminUpdConfigRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *AdminUpdConfigRsp) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

type AdminGetConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminGetConfigReq) Reset()         { *m = AdminGetConfigReq{} }
func (m *AdminGetConfigReq) String() string { return proto.CompactTextString(m) }
func (*AdminGetConfigReq) ProtoMessage()    {}
func (*AdminGetConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_96ad09d7473f4a36, []int{6}
}
func (m *AdminGetConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminGetConfigReq.Unmarshal(m, b)
}
func (m *AdminGetConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminGetConfigReq.Marshal(b, m, deterministic)
}
func (dst *AdminGetConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminGetConfigReq.Merge(dst, src)
}
func (m *AdminGetConfigReq) XXX_Size() int {
	return xxx_messageInfo_AdminGetConfigReq.Size(m)
}
func (m *AdminGetConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminGetConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminGetConfigReq proto.InternalMessageInfo

func (m *AdminGetConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

type AdminGetConfigRsp struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Code                 *int32   `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	Keys                 []string `protobuf:"bytes,3,rep,name=keys" json:"keys,omitempty"`
	Values               []string `protobuf:"bytes,4,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminGetConfigRsp) Reset()         { *m = AdminGetConfigRsp{} }
func (m *AdminGetConfigRsp) String() string { return proto.CompactTextString(m) }
func (*AdminGetConfigRsp) ProtoMessage()    {}
func (*AdminGetConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_96ad09d7473f4a36, []int{7}
}
func (m *AdminGetConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminGetConfigRsp.Unmarshal(m, b)
}
func (m *AdminGetConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminGetConfigRsp.Marshal(b, m, deterministic)
}
func (dst *AdminGetConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminGetConfigRsp.Merge(dst, src)
}
func (m *AdminGetConfigRsp) XXX_Size() int {
	return xxx_messageInfo_AdminGetConfigRsp.Size(m)
}
func (m *AdminGetConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminGetConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AdminGetConfigRsp proto.InternalMessageInfo

func (m *AdminGetConfigRsp) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *AdminGetConfigRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *AdminGetConfigRsp) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *AdminGetConfigRsp) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*AdminAddConfigReq)(nil), "protocol.AdminAddConfigReq")
	proto.RegisterType((*AdminAddConfigRsp)(nil), "protocol.AdminAddConfigRsp")
	proto.RegisterType((*AdminDelConfigReq)(nil), "protocol.AdminDelConfigReq")
	proto.RegisterType((*AdminDelConfigRsp)(nil), "protocol.AdminDelConfigRsp")
	proto.RegisterType((*AdminUpdConfigReq)(nil), "protocol.AdminUpdConfigReq")
	proto.RegisterType((*AdminUpdConfigRsp)(nil), "protocol.AdminUpdConfigRsp")
	proto.RegisterType((*AdminGetConfigReq)(nil), "protocol.AdminGetConfigReq")
	proto.RegisterType((*AdminGetConfigRsp)(nil), "protocol.AdminGetConfigRsp")
	proto.RegisterEnum("protocol.AdminMsgTypeId", AdminMsgTypeId_name, AdminMsgTypeId_value)
}

func init() {
	proto.RegisterFile("admin_protocol.proto", fileDescriptor_admin_protocol_96ad09d7473f4a36)
}

var fileDescriptor_admin_protocol_96ad09d7473f4a36 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x52, 0x4b, 0x4b, 0xfb, 0x40,
	0x10, 0xa7, 0x49, 0xfe, 0x7f, 0xda, 0xb1, 0x94, 0x75, 0x7d, 0x74, 0x7d, 0x1c, 0x42, 0x2e, 0x06,
	0x0f, 0x82, 0x1f, 0xa1, 0x28, 0xca, 0x22, 0x5e, 0x7c, 0xe1, 0x4d, 0x4a, 0x66, 0x0c, 0xa1, 0x69,
	0x76, 0xcd, 0xd6, 0x4a, 0xbe, 0xa9, 0x1f, 0x47, 0xb2, 0x36, 0x69, 0x20, 0xc1, 0x1e, 0xc4, 0xdb,
	0xce, 0xfc, 0xe6, 0xf7, 0x60, 0x66, 0x61, 0x77, 0x8a, 0xf3, 0x24, 0x7b, 0xd1, 0xb9, 0x5a, 0xa8,
	0x48, 0xa5, 0x67, 0xf6, 0xc1, 0xfb, 0x55, 0x1d, 0x3c, 0xc3, 0xf6, 0xa4, 0x9c, 0x98, 0x20, 0x5e,
	0xa8, 0xec, 0x35, 0x89, 0xef, 0xe8, 0x8d, 0x73, 0x00, 0x43, 0xf9, 0x32, 0x89, 0xe8, 0x86, 0x0a,
	0xd1, 0xf3, 0x9d, 0x70, 0xc0, 0xb7, 0xc0, 0x9d, 0x51, 0x21, 0x1c, 0x5b, 0x30, 0xe8, 0xab, 0x14,
	0x9f, 0xa6, 0xe9, 0x3b, 0x09, 0xb7, 0xea, 0x64, 0xf4, 0xf1, 0xdd, 0xf1, 0xca, 0x4e, 0x70, 0xde,
	0x52, 0x36, 0x9a, 0x0f, 0xc1, 0x8b, 0x14, 0x92, 0xd5, 0xfc, 0xc7, 0x47, 0xf0, 0x9f, 0xf2, 0x7c,
	0x6e, 0x62, 0xe1, 0xf8, 0xbd, 0x70, 0x10, 0x5c, 0xad, 0x28, 0x97, 0x94, 0xfe, 0x26, 0x4c, 0x6d,
	0xbd, 0xd6, 0xd9, 0x68, 0x5d, 0xed, 0xe1, 0x51, 0xff, 0xd5, 0x1e, 0xd6, 0xca, 0x1b, 0xc3, 0x9c,
	0xac, 0x28, 0xd7, 0xb4, 0xf8, 0x31, 0x4c, 0x70, 0xdf, 0x1a, 0x34, 0xba, 0x33, 0x75, 0xe5, 0xe7,
	0x58, 0xbf, 0x21, 0x78, 0x33, 0x2a, 0x8c, 0x70, 0x7d, 0x37, 0x1c, 0x94, 0xee, 0xcb, 0x32, 0xaf,
	0x11, 0x5e, 0x59, 0x9f, 0x7e, 0xf6, 0x60, 0x64, 0x55, 0x6f, 0x4d, 0xfc, 0x50, 0x68, 0x92, 0xc8,
	0xc7, 0xb0, 0xd3, 0xfa, 0x25, 0x12, 0xd9, 0x5e, 0x07, 0x60, 0xb4, 0x44, 0xb6, 0x5f, 0x03, 0xcd,
	0x53, 0x4a, 0x64, 0xe3, 0x0e, 0xc0, 0x32, 0x44, 0x0d, 0x34, 0x2f, 0x20, 0x91, 0x1d, 0x74, 0x00,
	0x96, 0x71, 0x58, 0x03, 0xcd, 0x35, 0x49, 0x64, 0x47, 0x1d, 0x80, 0x65, 0x1c, 0x7f, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x10, 0x4d, 0x64, 0xaf, 0x0e, 0x03, 0x00, 0x00,
}
