// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin_protocol.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdminAddConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	ConfKeys             []string `protobuf:"bytes,2,rep,name=confKeys" json:"confKeys,omitempty"`
	Values               []string `protobuf:"bytes,3,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminAddConfigReq) Reset()         { *m = AdminAddConfigReq{} }
func (m *AdminAddConfigReq) String() string { return proto.CompactTextString(m) }
func (*AdminAddConfigReq) ProtoMessage()    {}
func (*AdminAddConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_48863793af79f907, []int{0}
}
func (m *AdminAddConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminAddConfigReq.Unmarshal(m, b)
}
func (m *AdminAddConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminAddConfigReq.Marshal(b, m, deterministic)
}
func (dst *AdminAddConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminAddConfigReq.Merge(dst, src)
}
func (m *AdminAddConfigReq) XXX_Size() int {
	return xxx_messageInfo_AdminAddConfigReq.Size(m)
}
func (m *AdminAddConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminAddConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminAddConfigReq proto.InternalMessageInfo

func (m *AdminAddConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *AdminAddConfigReq) GetConfKeys() []string {
	if m != nil {
		return m.ConfKeys
	}
	return nil
}

func (m *AdminAddConfigReq) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type AdminDelConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Version              *uint32  `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminDelConfigReq) Reset()         { *m = AdminDelConfigReq{} }
func (m *AdminDelConfigReq) String() string { return proto.CompactTextString(m) }
func (*AdminDelConfigReq) ProtoMessage()    {}
func (*AdminDelConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_48863793af79f907, []int{1}
}
func (m *AdminDelConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminDelConfigReq.Unmarshal(m, b)
}
func (m *AdminDelConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminDelConfigReq.Marshal(b, m, deterministic)
}
func (dst *AdminDelConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminDelConfigReq.Merge(dst, src)
}
func (m *AdminDelConfigReq) XXX_Size() int {
	return xxx_messageInfo_AdminDelConfigReq.Size(m)
}
func (m *AdminDelConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminDelConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminDelConfigReq proto.InternalMessageInfo

func (m *AdminDelConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *AdminDelConfigReq) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type AdminUpdConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Version              *uint32  `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	ConfKeys             []string `protobuf:"bytes,3,rep,name=confKeys" json:"confKeys,omitempty"`
	Values               []string `protobuf:"bytes,4,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminUpdConfigReq) Reset()         { *m = AdminUpdConfigReq{} }
func (m *AdminUpdConfigReq) String() string { return proto.CompactTextString(m) }
func (*AdminUpdConfigReq) ProtoMessage()    {}
func (*AdminUpdConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_48863793af79f907, []int{2}
}
func (m *AdminUpdConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUpdConfigReq.Unmarshal(m, b)
}
func (m *AdminUpdConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUpdConfigReq.Marshal(b, m, deterministic)
}
func (dst *AdminUpdConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUpdConfigReq.Merge(dst, src)
}
func (m *AdminUpdConfigReq) XXX_Size() int {
	return xxx_messageInfo_AdminUpdConfigReq.Size(m)
}
func (m *AdminUpdConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUpdConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUpdConfigReq proto.InternalMessageInfo

func (m *AdminUpdConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *AdminUpdConfigReq) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *AdminUpdConfigReq) GetConfKeys() []string {
	if m != nil {
		return m.ConfKeys
	}
	return nil
}

func (m *AdminUpdConfigReq) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type AdminExecuteRsp struct {
	Code                 *int32   `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Error                *string  `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminExecuteRsp) Reset()         { *m = AdminExecuteRsp{} }
func (m *AdminExecuteRsp) String() string { return proto.CompactTextString(m) }
func (*AdminExecuteRsp) ProtoMessage()    {}
func (*AdminExecuteRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_48863793af79f907, []int{3}
}
func (m *AdminExecuteRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminExecuteRsp.Unmarshal(m, b)
}
func (m *AdminExecuteRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminExecuteRsp.Marshal(b, m, deterministic)
}
func (dst *AdminExecuteRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminExecuteRsp.Merge(dst, src)
}
func (m *AdminExecuteRsp) XXX_Size() int {
	return xxx_messageInfo_AdminExecuteRsp.Size(m)
}
func (m *AdminExecuteRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminExecuteRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AdminExecuteRsp proto.InternalMessageInfo

func (m *AdminExecuteRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *AdminExecuteRsp) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type AdminGetConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminGetConfigReq) Reset()         { *m = AdminGetConfigReq{} }
func (m *AdminGetConfigReq) String() string { return proto.CompactTextString(m) }
func (*AdminGetConfigReq) ProtoMessage()    {}
func (*AdminGetConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_48863793af79f907, []int{4}
}
func (m *AdminGetConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminGetConfigReq.Unmarshal(m, b)
}
func (m *AdminGetConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminGetConfigReq.Marshal(b, m, deterministic)
}
func (dst *AdminGetConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminGetConfigReq.Merge(dst, src)
}
func (m *AdminGetConfigReq) XXX_Size() int {
	return xxx_messageInfo_AdminGetConfigReq.Size(m)
}
func (m *AdminGetConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminGetConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_AdminGetConfigReq proto.InternalMessageInfo

func (m *AdminGetConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

type AdminGetConfigRsp struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Code                 *int32   `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	Version              *uint32  `protobuf:"varint,3,req,name=version" json:"version,omitempty"`
	ConfKeys             []string `protobuf:"bytes,4,rep,name=confKeys" json:"confKeys,omitempty"`
	Values               []string `protobuf:"bytes,5,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminGetConfigRsp) Reset()         { *m = AdminGetConfigRsp{} }
func (m *AdminGetConfigRsp) String() string { return proto.CompactTextString(m) }
func (*AdminGetConfigRsp) ProtoMessage()    {}
func (*AdminGetConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_admin_protocol_48863793af79f907, []int{5}
}
func (m *AdminGetConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminGetConfigRsp.Unmarshal(m, b)
}
func (m *AdminGetConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminGetConfigRsp.Marshal(b, m, deterministic)
}
func (dst *AdminGetConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminGetConfigRsp.Merge(dst, src)
}
func (m *AdminGetConfigRsp) XXX_Size() int {
	return xxx_messageInfo_AdminGetConfigRsp.Size(m)
}
func (m *AdminGetConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminGetConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AdminGetConfigRsp proto.InternalMessageInfo

func (m *AdminGetConfigRsp) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *AdminGetConfigRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *AdminGetConfigRsp) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *AdminGetConfigRsp) GetConfKeys() []string {
	if m != nil {
		return m.ConfKeys
	}
	return nil
}

func (m *AdminGetConfigRsp) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*AdminAddConfigReq)(nil), "protocol.AdminAddConfigReq")
	proto.RegisterType((*AdminDelConfigReq)(nil), "protocol.AdminDelConfigReq")
	proto.RegisterType((*AdminUpdConfigReq)(nil), "protocol.AdminUpdConfigReq")
	proto.RegisterType((*AdminExecuteRsp)(nil), "protocol.AdminExecuteRsp")
	proto.RegisterType((*AdminGetConfigReq)(nil), "protocol.AdminGetConfigReq")
	proto.RegisterType((*AdminGetConfigRsp)(nil), "protocol.AdminGetConfigRsp")
}

func init() {
	proto.RegisterFile("admin_protocol.proto", fileDescriptor_admin_protocol_48863793af79f907)
}

var fileDescriptor_admin_protocol_48863793af79f907 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x8f, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x69, 0x76, 0x57, 0xbb, 0x83, 0xb5, 0x1a, 0x3c, 0xe4, 0x18, 0x72, 0x31, 0xa7, 0x9e,
	0xbd, 0x16, 0x15, 0x91, 0xde, 0x0a, 0x5e, 0xbc, 0x48, 0x49, 0xa6, 0x1a, 0x58, 0x33, 0x31, 0xd9,
	0x2e, 0xf6, 0xdf, 0xcb, 0x86, 0x2d, 0x68, 0x2b, 0x85, 0xde, 0xe6, 0xc1, 0xcc, 0x37, 0xdf, 0x83,
	0x9b, 0x95, 0xfd, 0x74, 0xfe, 0x2d, 0x44, 0x6a, 0xc9, 0x50, 0x33, 0xcb, 0x03, 0x1f, 0xef, 0xb2,
	0x7a, 0x86, 0xeb, 0x79, 0xbf, 0x31, 0xb7, 0xf6, 0x9e, 0xfc, 0xda, 0xbd, 0x2f, 0xf1, 0x8b, 0x73,
	0x80, 0x84, 0xb1, 0x73, 0x06, 0x17, 0xb8, 0x15, 0x23, 0xc9, 0x74, 0xcd, 0xaf, 0x60, 0x6c, 0xc8,
	0xaf, 0x17, 0xb8, 0x4d, 0x82, 0xc9, 0x42, 0xd7, 0xfc, 0x12, 0xce, 0xba, 0x55, 0xb3, 0xc1, 0x24,
	0x8a, 0x3e, 0xab, 0xbb, 0x01, 0xf5, 0x80, 0xcd, 0x71, 0xd4, 0x14, 0xce, 0x3b, 0x8c, 0xc9, 0x91,
	0x17, 0x4c, 0x32, 0x3d, 0x51, 0xaf, 0xc3, 0xe5, 0x4b, 0xb0, 0xa7, 0x5d, 0xfe, 0xb1, 0x2a, 0xf6,
	0xac, 0xca, 0x6c, 0x35, 0x83, 0x69, 0x66, 0x3f, 0x7e, 0xa3, 0xd9, 0xb4, 0xb8, 0x4c, 0x81, 0x5f,
	0x40, 0x69, 0xc8, 0x62, 0x66, 0x56, 0x7c, 0x02, 0x15, 0xc6, 0x48, 0x51, 0x30, 0x39, 0xd2, 0xb5,
	0xba, 0x1d, 0x5c, 0x9e, 0xb0, 0x3d, 0xea, 0xa2, 0x3e, 0x0e, 0x16, 0x53, 0xf8, 0x57, 0x7a, 0xf7,
	0x8e, 0xe5, 0x77, 0xbf, 0x2a, 0x14, 0x07, 0x15, 0xca, 0xbd, 0x0a, 0x55, 0x9f, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x42, 0x19, 0x5e, 0x98, 0xc4, 0x01, 0x00, 0x00,
}
