// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgTypeId int32

const (
	MsgTypeId_SubscribeReqId         MsgTypeId = 1
	MsgTypeId_SubscribeBrokerRspId   MsgTypeId = 2
	MsgTypeId_SubscribeAgentRspId    MsgTypeId = 3
	MsgTypeId_AddConfigReqId         MsgTypeId = 4
	MsgTypeId_DelConfigReqId         MsgTypeId = 5
	MsgTypeId_DelServiceConfigReqId  MsgTypeId = 6
	MsgTypeId_UpdateConfigReqId      MsgTypeId = 7
	MsgTypeId_PullServiceConfigReqId MsgTypeId = 8
	MsgTypeId_PullServiceConfigRspId MsgTypeId = 9
)

var MsgTypeId_name = map[int32]string{
	1: "SubscribeReqId",
	2: "SubscribeBrokerRspId",
	3: "SubscribeAgentRspId",
	4: "AddConfigReqId",
	5: "DelConfigReqId",
	6: "DelServiceConfigReqId",
	7: "UpdateConfigReqId",
	8: "PullServiceConfigReqId",
	9: "PullServiceConfigRspId",
}
var MsgTypeId_value = map[string]int32{
	"SubscribeReqId":         1,
	"SubscribeBrokerRspId":   2,
	"SubscribeAgentRspId":    3,
	"AddConfigReqId":         4,
	"DelConfigReqId":         5,
	"DelServiceConfigReqId":  6,
	"UpdateConfigReqId":      7,
	"PullServiceConfigReqId": 8,
	"PullServiceConfigRspId": 9,
}

func (x MsgTypeId) Enum() *MsgTypeId {
	p := new(MsgTypeId)
	*p = x
	return p
}
func (x MsgTypeId) String() string {
	return proto.EnumName(MsgTypeId_name, int32(x))
}
func (x *MsgTypeId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgTypeId_value, data, "MsgTypeId")
	if err != nil {
		return err
	}
	*x = MsgTypeId(value)
	return nil
}
func (MsgTypeId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agent_af89246131cb6230, []int{0}
}

// client向agent发起订阅请求,agent向broker发起订阅请求
type SubscribeReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeReq) Reset()         { *m = SubscribeReq{} }
func (m *SubscribeReq) String() string { return proto.CompactTextString(m) }
func (*SubscribeReq) ProtoMessage()    {}
func (*SubscribeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_af89246131cb6230, []int{0}
}
func (m *SubscribeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeReq.Unmarshal(m, b)
}
func (m *SubscribeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeReq.Marshal(b, m, deterministic)
}
func (dst *SubscribeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeReq.Merge(dst, src)
}
func (m *SubscribeReq) XXX_Size() int {
	return xxx_messageInfo_SubscribeReq.Size(m)
}
func (m *SubscribeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeReq proto.InternalMessageInfo

func (m *SubscribeReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

// broker向agent回复订阅请求
type SubscribeBrokerRsp struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Code                 *int32   `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	Keys                 []string `protobuf:"bytes,3,rep,name=keys" json:"keys,omitempty"`
	Values               []string `protobuf:"bytes,4,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeBrokerRsp) Reset()         { *m = SubscribeBrokerRsp{} }
func (m *SubscribeBrokerRsp) String() string { return proto.CompactTextString(m) }
func (*SubscribeBrokerRsp) ProtoMessage()    {}
func (*SubscribeBrokerRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_af89246131cb6230, []int{1}
}
func (m *SubscribeBrokerRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeBrokerRsp.Unmarshal(m, b)
}
func (m *SubscribeBrokerRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeBrokerRsp.Marshal(b, m, deterministic)
}
func (dst *SubscribeBrokerRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeBrokerRsp.Merge(dst, src)
}
func (m *SubscribeBrokerRsp) XXX_Size() int {
	return xxx_messageInfo_SubscribeBrokerRsp.Size(m)
}
func (m *SubscribeBrokerRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeBrokerRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeBrokerRsp proto.InternalMessageInfo

func (m *SubscribeBrokerRsp) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *SubscribeBrokerRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *SubscribeBrokerRsp) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *SubscribeBrokerRsp) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// agent向client回复订阅请求
type SubscribeAgentRsp struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Code                 *int32   `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeAgentRsp) Reset()         { *m = SubscribeAgentRsp{} }
func (m *SubscribeAgentRsp) String() string { return proto.CompactTextString(m) }
func (*SubscribeAgentRsp) ProtoMessage()    {}
func (*SubscribeAgentRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_af89246131cb6230, []int{2}
}
func (m *SubscribeAgentRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeAgentRsp.Unmarshal(m, b)
}
func (m *SubscribeAgentRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeAgentRsp.Marshal(b, m, deterministic)
}
func (dst *SubscribeAgentRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeAgentRsp.Merge(dst, src)
}
func (m *SubscribeAgentRsp) XXX_Size() int {
	return xxx_messageInfo_SubscribeAgentRsp.Size(m)
}
func (m *SubscribeAgentRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeAgentRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeAgentRsp proto.InternalMessageInfo

func (m *SubscribeAgentRsp) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *SubscribeAgentRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

// broker向client推送添加一个配置项命令
type AddConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Key                  *string  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,3,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddConfigReq) Reset()         { *m = AddConfigReq{} }
func (m *AddConfigReq) String() string { return proto.CompactTextString(m) }
func (*AddConfigReq) ProtoMessage()    {}
func (*AddConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_af89246131cb6230, []int{3}
}
func (m *AddConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddConfigReq.Unmarshal(m, b)
}
func (m *AddConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddConfigReq.Marshal(b, m, deterministic)
}
func (dst *AddConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddConfigReq.Merge(dst, src)
}
func (m *AddConfigReq) XXX_Size() int {
	return xxx_messageInfo_AddConfigReq.Size(m)
}
func (m *AddConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddConfigReq proto.InternalMessageInfo

func (m *AddConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *AddConfigReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *AddConfigReq) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

// broker向client发起删除一个配置项命令
type DelConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Key                  *string  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelConfigReq) Reset()         { *m = DelConfigReq{} }
func (m *DelConfigReq) String() string { return proto.CompactTextString(m) }
func (*DelConfigReq) ProtoMessage()    {}
func (*DelConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_af89246131cb6230, []int{4}
}
func (m *DelConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelConfigReq.Unmarshal(m, b)
}
func (m *DelConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelConfigReq.Marshal(b, m, deterministic)
}
func (dst *DelConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelConfigReq.Merge(dst, src)
}
func (m *DelConfigReq) XXX_Size() int {
	return xxx_messageInfo_DelConfigReq.Size(m)
}
func (m *DelConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelConfigReq proto.InternalMessageInfo

func (m *DelConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *DelConfigReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

// broker向client发起一个服务的全部删除配置项命令
type DelServiceConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelServiceConfigReq) Reset()         { *m = DelServiceConfigReq{} }
func (m *DelServiceConfigReq) String() string { return proto.CompactTextString(m) }
func (*DelServiceConfigReq) ProtoMessage()    {}
func (*DelServiceConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_af89246131cb6230, []int{5}
}
func (m *DelServiceConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelServiceConfigReq.Unmarshal(m, b)
}
func (m *DelServiceConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelServiceConfigReq.Marshal(b, m, deterministic)
}
func (dst *DelServiceConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelServiceConfigReq.Merge(dst, src)
}
func (m *DelServiceConfigReq) XXX_Size() int {
	return xxx_messageInfo_DelServiceConfigReq.Size(m)
}
func (m *DelServiceConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelServiceConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelServiceConfigReq proto.InternalMessageInfo

func (m *DelServiceConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

// broker向client发起更新一个配置项的命令
type UpdateConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Key                  *string  `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,3,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConfigReq) Reset()         { *m = UpdateConfigReq{} }
func (m *UpdateConfigReq) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigReq) ProtoMessage()    {}
func (*UpdateConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_af89246131cb6230, []int{6}
}
func (m *UpdateConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigReq.Unmarshal(m, b)
}
func (m *UpdateConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigReq.Marshal(b, m, deterministic)
}
func (dst *UpdateConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigReq.Merge(dst, src)
}
func (m *UpdateConfigReq) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigReq.Size(m)
}
func (m *UpdateConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigReq proto.InternalMessageInfo

func (m *UpdateConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *UpdateConfigReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *UpdateConfigReq) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

// agent向broker拉取一个服务的最新配置
type PullServiceConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullServiceConfigReq) Reset()         { *m = PullServiceConfigReq{} }
func (m *PullServiceConfigReq) String() string { return proto.CompactTextString(m) }
func (*PullServiceConfigReq) ProtoMessage()    {}
func (*PullServiceConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_af89246131cb6230, []int{7}
}
func (m *PullServiceConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullServiceConfigReq.Unmarshal(m, b)
}
func (m *PullServiceConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullServiceConfigReq.Marshal(b, m, deterministic)
}
func (dst *PullServiceConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullServiceConfigReq.Merge(dst, src)
}
func (m *PullServiceConfigReq) XXX_Size() int {
	return xxx_messageInfo_PullServiceConfigReq.Size(m)
}
func (m *PullServiceConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PullServiceConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_PullServiceConfigReq proto.InternalMessageInfo

func (m *PullServiceConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

// broker回复agent一个服务的最新配置
type PullServiceConfigRsp struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=keys" json:"keys,omitempty"`
	Values               []string `protobuf:"bytes,3,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullServiceConfigRsp) Reset()         { *m = PullServiceConfigRsp{} }
func (m *PullServiceConfigRsp) String() string { return proto.CompactTextString(m) }
func (*PullServiceConfigRsp) ProtoMessage()    {}
func (*PullServiceConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_af89246131cb6230, []int{8}
}
func (m *PullServiceConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullServiceConfigRsp.Unmarshal(m, b)
}
func (m *PullServiceConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullServiceConfigRsp.Marshal(b, m, deterministic)
}
func (dst *PullServiceConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullServiceConfigRsp.Merge(dst, src)
}
func (m *PullServiceConfigRsp) XXX_Size() int {
	return xxx_messageInfo_PullServiceConfigRsp.Size(m)
}
func (m *PullServiceConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PullServiceConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PullServiceConfigRsp proto.InternalMessageInfo

func (m *PullServiceConfigRsp) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *PullServiceConfigRsp) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *PullServiceConfigRsp) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*SubscribeReq)(nil), "protocol.SubscribeReq")
	proto.RegisterType((*SubscribeBrokerRsp)(nil), "protocol.SubscribeBrokerRsp")
	proto.RegisterType((*SubscribeAgentRsp)(nil), "protocol.SubscribeAgentRsp")
	proto.RegisterType((*AddConfigReq)(nil), "protocol.AddConfigReq")
	proto.RegisterType((*DelConfigReq)(nil), "protocol.DelConfigReq")
	proto.RegisterType((*DelServiceConfigReq)(nil), "protocol.DelServiceConfigReq")
	proto.RegisterType((*UpdateConfigReq)(nil), "protocol.UpdateConfigReq")
	proto.RegisterType((*PullServiceConfigReq)(nil), "protocol.PullServiceConfigReq")
	proto.RegisterType((*PullServiceConfigRsp)(nil), "protocol.PullServiceConfigRsp")
	proto.RegisterEnum("protocol.MsgTypeId", MsgTypeId_name, MsgTypeId_value)
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_agent_af89246131cb6230) }

var fileDescriptor_agent_af89246131cb6230 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x0d, 0x2d, 0x20, 0x1d, 0x2a, 0x2e, 0x03, 0x68, 0xf5, 0x44, 0xf6, 0x84, 0x1c, 0xf4, 0xe4,
	0xd5, 0x04, 0xe5, 0xe0, 0xc6, 0x98, 0x18, 0xc0, 0x0f, 0x80, 0xce, 0x48, 0x08, 0x0d, 0x5b, 0xbb,
	0x40, 0xd2, 0xff, 0xf5, 0x43, 0x4c, 0xd7, 0x84, 0x10, 0x28, 0xa6, 0xf1, 0xb4, 0x99, 0xdd, 0x37,
	0x6f, 0xde, 0xbe, 0x37, 0x50, 0x9f, 0xce, 0x79, 0xb5, 0xbe, 0x8b, 0x13, 0xbd, 0xd6, 0x58, 0xb3,
	0x47, 0xa8, 0x23, 0x29, 0xc1, 0x1f, 0x6f, 0x66, 0x26, 0x4c, 0x16, 0x33, 0x1e, 0xf1, 0x17, 0x22,
	0x80, 0xe1, 0x64, 0xbb, 0x08, 0xf9, 0x95, 0xd3, 0xa0, 0xd4, 0x75, 0x7a, 0x9e, 0x9c, 0x00, 0xee,
	0x30, 0x4f, 0x89, 0x5e, 0x72, 0x32, 0x32, 0x71, 0x1e, 0x12, 0x7d, 0x28, 0x87, 0x9a, 0x38, 0x70,
	0xba, 0x4e, 0xaf, 0x92, 0x55, 0x4b, 0x4e, 0x4d, 0xe0, 0x76, 0xdd, 0x9e, 0x87, 0x0d, 0xa8, 0x6e,
	0xa7, 0xd1, 0x86, 0x4d, 0x50, 0xce, 0x6a, 0xf9, 0x00, 0xcd, 0x1d, 0xeb, 0x20, 0xd3, 0x56, 0x88,
	0x54, 0x3e, 0x82, 0x3f, 0x20, 0x7a, 0xd6, 0xab, 0xcf, 0xc5, 0xfc, 0x84, 0x60, 0xac, 0x83, 0xbb,
	0xe4, 0xd4, 0x36, 0x78, 0x78, 0x0e, 0x15, 0x3b, 0x37, 0x70, 0xed, 0x67, 0xee, 0xc1, 0x1f, 0x72,
	0x54, 0xbc, 0x5f, 0xde, 0x42, 0x6b, 0xc8, 0xd1, 0xf8, 0x17, 0xf3, 0x67, 0x9f, 0x1c, 0xc0, 0xc5,
	0x47, 0x4c, 0xd3, 0x35, 0xff, 0x5f, 0x5e, 0x1f, 0xda, 0xef, 0x9b, 0xa8, 0xd8, 0xb8, 0x97, 0x3c,
	0xec, 0x69, 0x13, 0x6d, 0x16, 0xce, 0x41, 0x16, 0x36, 0x9b, 0xfe, 0x77, 0x09, 0xbc, 0x37, 0x33,
	0x9f, 0xa4, 0x31, 0x2b, 0x42, 0x84, 0xc6, 0xfe, 0x4e, 0x28, 0x12, 0x25, 0x0c, 0xa0, 0x7d, 0xbc,
	0x03, 0x8a, 0x84, 0x83, 0x57, 0xd0, 0x3a, 0xca, 0x51, 0x91, 0x70, 0x33, 0x9a, 0xfd, 0xa4, 0x14,
	0x89, 0x72, 0x76, 0xb7, 0xef, 0xbe, 0x22, 0x51, 0xc1, 0x6b, 0xe8, 0xe4, 0x18, 0xac, 0x48, 0x54,
	0xb1, 0x03, 0xcd, 0x03, 0x43, 0x15, 0x89, 0x33, 0xbc, 0x81, 0xcb, 0x3c, 0x93, 0x14, 0x89, 0x5a,
	0xfe, 0x9b, 0x55, 0xe4, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xdd, 0xfe, 0x38, 0x04, 0x03,
	0x00, 0x00,
}
