// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgTypeId int32

const (
	MsgTypeId_GetConfigReqId    MsgTypeId = 1
	MsgTypeId_GetConfigRspId    MsgTypeId = 2
	MsgTypeId_PushConfigReqId   MsgTypeId = 3
	MsgTypeId_RemoveConfigReqId MsgTypeId = 4
	MsgTypeId_PullConfigReqId   MsgTypeId = 5
	MsgTypeId_PullConfigRspId   MsgTypeId = 6
)

var MsgTypeId_name = map[int32]string{
	1: "GetConfigReqId",
	2: "GetConfigRspId",
	3: "PushConfigReqId",
	4: "RemoveConfigReqId",
	5: "PullConfigReqId",
	6: "PullConfigRspId",
}
var MsgTypeId_value = map[string]int32{
	"GetConfigReqId":    1,
	"GetConfigRspId":    2,
	"PushConfigReqId":   3,
	"RemoveConfigReqId": 4,
	"PullConfigReqId":   5,
	"PullConfigRspId":   6,
}

func (x MsgTypeId) Enum() *MsgTypeId {
	p := new(MsgTypeId)
	*p = x
	return p
}
func (x MsgTypeId) String() string {
	return proto.EnumName(MsgTypeId_name, int32(x))
}
func (x *MsgTypeId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgTypeId_value, data, "MsgTypeId")
	if err != nil {
		return err
	}
	*x = MsgTypeId(value)
	return nil
}
func (MsgTypeId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agent_b17cea0a41fc57a0, []int{0}
}

type GetConfigReq struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigReq) Reset()         { *m = GetConfigReq{} }
func (m *GetConfigReq) String() string { return proto.CompactTextString(m) }
func (*GetConfigReq) ProtoMessage()    {}
func (*GetConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_b17cea0a41fc57a0, []int{0}
}
func (m *GetConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigReq.Unmarshal(m, b)
}
func (m *GetConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigReq.Marshal(b, m, deterministic)
}
func (dst *GetConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigReq.Merge(dst, src)
}
func (m *GetConfigReq) XXX_Size() int {
	return xxx_messageInfo_GetConfigReq.Size(m)
}
func (m *GetConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigReq proto.InternalMessageInfo

func (m *GetConfigReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

type GetConfigRsp struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRsp) Reset()         { *m = GetConfigRsp{} }
func (m *GetConfigRsp) String() string { return proto.CompactTextString(m) }
func (*GetConfigRsp) ProtoMessage()    {}
func (*GetConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_b17cea0a41fc57a0, []int{1}
}
func (m *GetConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRsp.Unmarshal(m, b)
}
func (m *GetConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRsp.Marshal(b, m, deterministic)
}
func (dst *GetConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRsp.Merge(dst, src)
}
func (m *GetConfigRsp) XXX_Size() int {
	return xxx_messageInfo_GetConfigRsp.Size(m)
}
func (m *GetConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRsp proto.InternalMessageInfo

func (m *GetConfigRsp) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *GetConfigRsp) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type PushConfigReq struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushConfigReq) Reset()         { *m = PushConfigReq{} }
func (m *PushConfigReq) String() string { return proto.CompactTextString(m) }
func (*PushConfigReq) ProtoMessage()    {}
func (*PushConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_b17cea0a41fc57a0, []int{2}
}
func (m *PushConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushConfigReq.Unmarshal(m, b)
}
func (m *PushConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushConfigReq.Marshal(b, m, deterministic)
}
func (dst *PushConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushConfigReq.Merge(dst, src)
}
func (m *PushConfigReq) XXX_Size() int {
	return xxx_messageInfo_PushConfigReq.Size(m)
}
func (m *PushConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushConfigReq proto.InternalMessageInfo

func (m *PushConfigReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *PushConfigReq) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type RemoveConfigReq struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveConfigReq) Reset()         { *m = RemoveConfigReq{} }
func (m *RemoveConfigReq) String() string { return proto.CompactTextString(m) }
func (*RemoveConfigReq) ProtoMessage()    {}
func (*RemoveConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_b17cea0a41fc57a0, []int{3}
}
func (m *RemoveConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveConfigReq.Unmarshal(m, b)
}
func (m *RemoveConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveConfigReq.Marshal(b, m, deterministic)
}
func (dst *RemoveConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveConfigReq.Merge(dst, src)
}
func (m *RemoveConfigReq) XXX_Size() int {
	return xxx_messageInfo_RemoveConfigReq.Size(m)
}
func (m *RemoveConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveConfigReq proto.InternalMessageInfo

func (m *RemoveConfigReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

type PullConfigReq struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullConfigReq) Reset()         { *m = PullConfigReq{} }
func (m *PullConfigReq) String() string { return proto.CompactTextString(m) }
func (*PullConfigReq) ProtoMessage()    {}
func (*PullConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_b17cea0a41fc57a0, []int{4}
}
func (m *PullConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullConfigReq.Unmarshal(m, b)
}
func (m *PullConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullConfigReq.Marshal(b, m, deterministic)
}
func (dst *PullConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullConfigReq.Merge(dst, src)
}
func (m *PullConfigReq) XXX_Size() int {
	return xxx_messageInfo_PullConfigReq.Size(m)
}
func (m *PullConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PullConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_PullConfigReq proto.InternalMessageInfo

func (m *PullConfigReq) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *PullConfigReq) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type PullConfigRsp struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullConfigRsp) Reset()         { *m = PullConfigRsp{} }
func (m *PullConfigRsp) String() string { return proto.CompactTextString(m) }
func (*PullConfigRsp) ProtoMessage()    {}
func (*PullConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_b17cea0a41fc57a0, []int{5}
}
func (m *PullConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullConfigRsp.Unmarshal(m, b)
}
func (m *PullConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullConfigRsp.Marshal(b, m, deterministic)
}
func (dst *PullConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullConfigRsp.Merge(dst, src)
}
func (m *PullConfigRsp) XXX_Size() int {
	return xxx_messageInfo_PullConfigRsp.Size(m)
}
func (m *PullConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PullConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PullConfigRsp proto.InternalMessageInfo

func (m *PullConfigRsp) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *PullConfigRsp) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*GetConfigReq)(nil), "protocol.GetConfigReq")
	proto.RegisterType((*GetConfigRsp)(nil), "protocol.GetConfigRsp")
	proto.RegisterType((*PushConfigReq)(nil), "protocol.PushConfigReq")
	proto.RegisterType((*RemoveConfigReq)(nil), "protocol.RemoveConfigReq")
	proto.RegisterType((*PullConfigReq)(nil), "protocol.PullConfigReq")
	proto.RegisterType((*PullConfigRsp)(nil), "protocol.PullConfigRsp")
	proto.RegisterEnum("protocol.MsgTypeId", MsgTypeId_name, MsgTypeId_value)
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_agent_b17cea0a41fc57a0) }

var fileDescriptor_agent_b17cea0a41fc57a0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4c, 0x4f, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0xd2,
	0x5c, 0x3c, 0xee, 0xa9, 0x25, 0xce, 0xf9, 0x79, 0x69, 0x99, 0xe9, 0x41, 0xa9, 0x85, 0x42, 0xdc,
	0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x4a, 0x5a, 0xc8, 0x92, 0xc5,
	0x05, 0x28, 0x92, 0x42, 0xbc, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x4c, 0x60, 0xb5,
	0xda, 0x5c, 0xbc, 0x01, 0xa5, 0xc5, 0x19, 0xd8, 0x4d, 0x42, 0x57, 0x2c, 0xc7, 0xc5, 0x1f, 0x94,
	0x9a, 0x9b, 0x5f, 0x96, 0x8a, 0xc3, 0x62, 0x5d, 0x90, 0x61, 0x39, 0x39, 0x08, 0x59, 0x1e, 0x2e,
	0x96, 0xec, 0xd4, 0xca, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x4e, 0x21, 0x3e, 0x2e, 0x36, 0xb0,
	0x69, 0xc5, 0x12, 0x4c, 0x20, 0x3e, 0x9a, 0xf2, 0xe2, 0x02, 0xfc, 0xca, 0xb5, 0x3a, 0x19, 0xb9,
	0x38, 0x7d, 0x8b, 0xd3, 0x43, 0x2a, 0x0b, 0x52, 0x3d, 0x53, 0x84, 0x84, 0xb8, 0xf8, 0x90, 0x43,
	0xc0, 0x33, 0x45, 0x80, 0x11, 0x55, 0xac, 0xb8, 0xc0, 0x33, 0x45, 0x80, 0x49, 0x48, 0x98, 0x8b,
	0x1f, 0xc5, 0x83, 0x9e, 0x29, 0x02, 0xcc, 0x42, 0xa2, 0x5c, 0x82, 0x68, 0x1e, 0xf1, 0x4c, 0x11,
	0x60, 0x81, 0xa8, 0x45, 0x72, 0xbf, 0x67, 0x8a, 0x00, 0x2b, 0x9a, 0x20, 0xd8, 0x54, 0x36, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0xb9, 0x3e, 0xfd, 0x97, 0x01, 0x00, 0x00,
}
