// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base_protocol.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// client向agent发起使用中请求
type KeepUsingReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepUsingReq) Reset()         { *m = KeepUsingReq{} }
func (m *KeepUsingReq) String() string { return proto.CompactTextString(m) }
func (*KeepUsingReq) ProtoMessage()    {}
func (*KeepUsingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_protocol_fc7c47516cddbcd4, []int{0}
}
func (m *KeepUsingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepUsingReq.Unmarshal(m, b)
}
func (m *KeepUsingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepUsingReq.Marshal(b, m, deterministic)
}
func (dst *KeepUsingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepUsingReq.Merge(dst, src)
}
func (m *KeepUsingReq) XXX_Size() int {
	return xxx_messageInfo_KeepUsingReq.Size(m)
}
func (m *KeepUsingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepUsingReq.DiscardUnknown(m)
}

var xxx_messageInfo_KeepUsingReq proto.InternalMessageInfo

func (m *KeepUsingReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

// client向agent发起订阅请求,agent向broker发起订阅请求
type SubscribeReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeReq) Reset()         { *m = SubscribeReq{} }
func (m *SubscribeReq) String() string { return proto.CompactTextString(m) }
func (*SubscribeReq) ProtoMessage()    {}
func (*SubscribeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_protocol_fc7c47516cddbcd4, []int{1}
}
func (m *SubscribeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeReq.Unmarshal(m, b)
}
func (m *SubscribeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeReq.Marshal(b, m, deterministic)
}
func (dst *SubscribeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeReq.Merge(dst, src)
}
func (m *SubscribeReq) XXX_Size() int {
	return xxx_messageInfo_SubscribeReq.Size(m)
}
func (m *SubscribeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeReq proto.InternalMessageInfo

func (m *SubscribeReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

// broker向agent回复订阅请求
type SubscribeBrokerRsp struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Code                 *int32   `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	Version              *uint32  `protobuf:"varint,3,req,name=version" json:"version,omitempty"`
	ConfKeys             []string `protobuf:"bytes,4,rep,name=confKeys" json:"confKeys,omitempty"`
	Values               []string `protobuf:"bytes,5,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeBrokerRsp) Reset()         { *m = SubscribeBrokerRsp{} }
func (m *SubscribeBrokerRsp) String() string { return proto.CompactTextString(m) }
func (*SubscribeBrokerRsp) ProtoMessage()    {}
func (*SubscribeBrokerRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_protocol_fc7c47516cddbcd4, []int{2}
}
func (m *SubscribeBrokerRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeBrokerRsp.Unmarshal(m, b)
}
func (m *SubscribeBrokerRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeBrokerRsp.Marshal(b, m, deterministic)
}
func (dst *SubscribeBrokerRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeBrokerRsp.Merge(dst, src)
}
func (m *SubscribeBrokerRsp) XXX_Size() int {
	return xxx_messageInfo_SubscribeBrokerRsp.Size(m)
}
func (m *SubscribeBrokerRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeBrokerRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeBrokerRsp proto.InternalMessageInfo

func (m *SubscribeBrokerRsp) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *SubscribeBrokerRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *SubscribeBrokerRsp) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *SubscribeBrokerRsp) GetConfKeys() []string {
	if m != nil {
		return m.ConfKeys
	}
	return nil
}

func (m *SubscribeBrokerRsp) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// agent向client回复订阅请求
type SubscribeAgentRsp struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Code                 *int32   `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeAgentRsp) Reset()         { *m = SubscribeAgentRsp{} }
func (m *SubscribeAgentRsp) String() string { return proto.CompactTextString(m) }
func (*SubscribeAgentRsp) ProtoMessage()    {}
func (*SubscribeAgentRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_protocol_fc7c47516cddbcd4, []int{3}
}
func (m *SubscribeAgentRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeAgentRsp.Unmarshal(m, b)
}
func (m *SubscribeAgentRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeAgentRsp.Marshal(b, m, deterministic)
}
func (dst *SubscribeAgentRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeAgentRsp.Merge(dst, src)
}
func (m *SubscribeAgentRsp) XXX_Size() int {
	return xxx_messageInfo_SubscribeAgentRsp.Size(m)
}
func (m *SubscribeAgentRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeAgentRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeAgentRsp proto.InternalMessageInfo

func (m *SubscribeAgentRsp) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *SubscribeAgentRsp) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

// broker推送给agent某服务的最新配置
type PushServiceConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Version              *uint32  `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	ConfKeys             []string `protobuf:"bytes,3,rep,name=confKeys" json:"confKeys,omitempty"`
	Values               []string `protobuf:"bytes,4,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushServiceConfigReq) Reset()         { *m = PushServiceConfigReq{} }
func (m *PushServiceConfigReq) String() string { return proto.CompactTextString(m) }
func (*PushServiceConfigReq) ProtoMessage()    {}
func (*PushServiceConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_protocol_fc7c47516cddbcd4, []int{4}
}
func (m *PushServiceConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushServiceConfigReq.Unmarshal(m, b)
}
func (m *PushServiceConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushServiceConfigReq.Marshal(b, m, deterministic)
}
func (dst *PushServiceConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushServiceConfigReq.Merge(dst, src)
}
func (m *PushServiceConfigReq) XXX_Size() int {
	return xxx_messageInfo_PushServiceConfigReq.Size(m)
}
func (m *PushServiceConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushServiceConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushServiceConfigReq proto.InternalMessageInfo

func (m *PushServiceConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *PushServiceConfigReq) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *PushServiceConfigReq) GetConfKeys() []string {
	if m != nil {
		return m.ConfKeys
	}
	return nil
}

func (m *PushServiceConfigReq) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// agent向broker拉取一个服务的最新配置
type PullServiceConfigReq struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Version              *uint32  `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullServiceConfigReq) Reset()         { *m = PullServiceConfigReq{} }
func (m *PullServiceConfigReq) String() string { return proto.CompactTextString(m) }
func (*PullServiceConfigReq) ProtoMessage()    {}
func (*PullServiceConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_protocol_fc7c47516cddbcd4, []int{5}
}
func (m *PullServiceConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullServiceConfigReq.Unmarshal(m, b)
}
func (m *PullServiceConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullServiceConfigReq.Marshal(b, m, deterministic)
}
func (dst *PullServiceConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullServiceConfigReq.Merge(dst, src)
}
func (m *PullServiceConfigReq) XXX_Size() int {
	return xxx_messageInfo_PullServiceConfigReq.Size(m)
}
func (m *PullServiceConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PullServiceConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_PullServiceConfigReq proto.InternalMessageInfo

func (m *PullServiceConfigReq) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *PullServiceConfigReq) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

// broker回复agent一个服务的最新配置
type PullServiceConfigRsp struct {
	ServiceKey           *string  `protobuf:"bytes,1,req,name=serviceKey" json:"serviceKey,omitempty"`
	Version              *uint32  `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	ConfKeys             []string `protobuf:"bytes,3,rep,name=confKeys" json:"confKeys,omitempty"`
	Values               []string `protobuf:"bytes,4,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullServiceConfigRsp) Reset()         { *m = PullServiceConfigRsp{} }
func (m *PullServiceConfigRsp) String() string { return proto.CompactTextString(m) }
func (*PullServiceConfigRsp) ProtoMessage()    {}
func (*PullServiceConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_base_protocol_fc7c47516cddbcd4, []int{6}
}
func (m *PullServiceConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullServiceConfigRsp.Unmarshal(m, b)
}
func (m *PullServiceConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullServiceConfigRsp.Marshal(b, m, deterministic)
}
func (dst *PullServiceConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullServiceConfigRsp.Merge(dst, src)
}
func (m *PullServiceConfigRsp) XXX_Size() int {
	return xxx_messageInfo_PullServiceConfigRsp.Size(m)
}
func (m *PullServiceConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PullServiceConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PullServiceConfigRsp proto.InternalMessageInfo

func (m *PullServiceConfigRsp) GetServiceKey() string {
	if m != nil && m.ServiceKey != nil {
		return *m.ServiceKey
	}
	return ""
}

func (m *PullServiceConfigRsp) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *PullServiceConfigRsp) GetConfKeys() []string {
	if m != nil {
		return m.ConfKeys
	}
	return nil
}

func (m *PullServiceConfigRsp) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*KeepUsingReq)(nil), "protocol.KeepUsingReq")
	proto.RegisterType((*SubscribeReq)(nil), "protocol.SubscribeReq")
	proto.RegisterType((*SubscribeBrokerRsp)(nil), "protocol.SubscribeBrokerRsp")
	proto.RegisterType((*SubscribeAgentRsp)(nil), "protocol.SubscribeAgentRsp")
	proto.RegisterType((*PushServiceConfigReq)(nil), "protocol.PushServiceConfigReq")
	proto.RegisterType((*PullServiceConfigReq)(nil), "protocol.PullServiceConfigReq")
	proto.RegisterType((*PullServiceConfigRsp)(nil), "protocol.PullServiceConfigRsp")
}

func init() { proto.RegisterFile("base_protocol.proto", fileDescriptor_base_protocol_fc7c47516cddbcd4) }

var fileDescriptor_base_protocol_fc7c47516cddbcd4 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x8f, 0xcf, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x31, 0xdb, 0x6a, 0x3b, 0xd4, 0x5f, 0xa3, 0x87, 0x1c, 0x43, 0x4e, 0x39, 0x79, 0xf3,
	0xe4, 0x49, 0x3d, 0xee, 0x45, 0x5a, 0x3c, 0x8a, 0x74, 0xe3, 0xb4, 0x06, 0x43, 0x66, 0xcd, 0x74,
	0x17, 0xfa, 0xdf, 0xcb, 0xb6, 0x58, 0xa4, 0xba, 0xa0, 0xde, 0x32, 0xf0, 0xe5, 0xbd, 0xef, 0xc1,
	0x45, 0x35, 0x17, 0x7a, 0xae, 0x33, 0xaf, 0xd8, 0x73, 0xbc, 0xda, 0x3c, 0x70, 0xf4, 0x79, 0x5b,
	0x0b, 0x93, 0x92, 0xa8, 0x7e, 0x94, 0x90, 0x96, 0x53, 0x7a, 0x47, 0x04, 0x10, 0xca, 0x6d, 0xf0,
	0x54, 0xd2, 0x5a, 0x1f, 0x18, 0xe5, 0xc6, 0x1d, 0x33, 0x6b, 0x2a, 0xf1, 0x39, 0x54, 0xd4, 0xc7,
	0x04, 0xc0, 0x1d, 0x73, 0x97, 0xf9, 0x8d, 0xf2, 0x54, 0xea, 0x9f, 0x48, 0x9c, 0xc0, 0xc0, 0xf3,
	0x0b, 0x69, 0x65, 0x94, 0x1b, 0xe2, 0x29, 0x1c, 0xb5, 0x94, 0x25, 0x70, 0xd2, 0x85, 0x51, 0xee,
	0x18, 0xcf, 0x60, 0xe4, 0x39, 0x2d, 0x4a, 0x5a, 0x8b, 0x1e, 0x98, 0xc2, 0x8d, 0xf1, 0x04, 0x0e,
	0xdb, 0x79, 0x6c, 0x48, 0xf4, 0xb0, 0xbb, 0xed, 0x35, 0x9c, 0xef, 0xaa, 0x6e, 0x97, 0x94, 0x56,
	0xbf, 0x6a, 0xb2, 0x4f, 0x70, 0xf9, 0xd0, 0xc8, 0xeb, 0x6c, 0x4b, 0xdd, 0x73, 0x5a, 0x84, 0xbe,
	0xc5, 0x5f, 0xad, 0xd4, 0x37, 0xab, 0x62, 0xcf, 0x6a, 0x63, 0x69, 0x6f, 0xba, 0xf8, 0x18, 0xff,
	0x15, 0xbf, 0x75, 0xdb, 0xff, 0xdc, 0xb3, 0xea, 0xef, 0x6e, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xca, 0xe7, 0x59, 0xfd, 0x04, 0x02, 0x00, 0x00,
}
